### ISSUE TITLE
Missing Options

### ISSUE THREAD

**Issue by adelphiaUK** [stefantalpalaru/deluge-default-trackers#21]
OK, I have managed to now get DefaultTracker working but the only way I can edit the file is manually as I'm not seeing anywhere within the preferences of Deluge GUI (Windows 10 x64) as you can see from the attached screenshot.

There is absolutely nothing in the log file (which is set at warning level during debugging and deleted during a restart of the Deluge server - Ubuntu 16.04 LTS).

It may be nice if somewhere you can write a set of installation and setup instructions for those of us that don't know / understand python. They may have been done already but I can't find them.

![2018-08-10](https://user-images.githubusercontent.com/1812102/43965313-d43ec49a-9cb6-11e8-916e-bcb8f051625d.png)

**Comment by stefantalpalaru** [comment]
I got rid of the "requests" dependency, so your problem should be fixed now.

**Comment by adelphiaUK** [comment]
Still not resolved. I have just done a refreshed installation of my server and I'm back to square one! No I've got to try and remember HOW I got them going last time! I think I have to manually create a list if I recall on the server.

**Comment by stefantalpalaru** [comment]
You probably can't install plugins on a remote server from the GUI. Just place the .egg file in the server's plugin directory ("~/.config/deluge/plugins/" on Linux) and restart the Deluge daemon.

**Comment by adelphiaUK** [comment]
Thanks. That worked!
